# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: test-package-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt;

        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Install pytest and dependencies
        run: |
          pip install pytest
        
      - name: Run tests with pytest
        run: |
          python -m pytest

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/

  package:
    name: "package"
    runs-on: ubuntu-latest

    steps:
      #Checkout source code
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m piip install --upgrade pip
          pip install -r requirements.txt
        
    # package applications into BUILD directory
      name: Create BUILD directory and copy necessary application files
      run: | 
        mkdir BUILD
        cp -r static BUILD/static # copy the static directory and contents
        cp -r templates BUILD/templates # copy the templates directory and contents
        cp -r app.py BUILD/app.py
        cp -r requirements.txt BUILD/requirements.txt
      
      name: Upload artifact for deployment jobs
      uses: actions/upload artifact@v2
      with:
        name: python-app
        path: |
          ./BUILD

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'sknderson-vtm-tank'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_27A0724736B24389B03AAE4C966C32BD }}

## code for this is done, just needs to get it uploaded through Azure? 